# Generated by Django 5.0.1 on 2024-02-29 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sports', 'sports'), ('education', 'education'), ('politics', 'politics'), ('administrative', 'administrative'), ('religious', 'religious')], max_length=200)),
                ('tittle', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='media')),
                ('text', models.TextField(max_length=1000)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
